### ISSUE TITLE
Question: what about authentication (401) and redirect (3xx) ?

### ISSUE THREAD

**Issue by cmebarrow** [k3po/specification.wseb#4]
For authentication and load balancing server needs to be able to respond with 401 or 307 (temporary redirect) to the initial create request, and client should handle it using standard HTTP semantics. Both of those are covered by the HTTP spec (on both client and server) but maybe we need to add some language to defer to HTTP spec. Currently the spec says "For any handshake response status code other than 201, the client MUST fail the emulated WebSocket connection." and "the server MUST generate an HTTP handshake response with the following characteristics.
the HTTP handshake response status MUST be 201".

We could say create is a standard HTTP request handed as such by both sides and must result in 201 response after any redirects or authenticaion

Note that If the http stack is httpxe...then httpxe handles it either by letting the real http stack under httpxe handle it (basic) or by httpxe handling it (application basic).

**Comment by jfallows** [comment]
We should definitely add language to indicate this is supported, but outside the scope of WSE.
